language: rust

cache: cargo

sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose --no-default-features
  - cargo test --verbose --no-default-features --features scott scott
  - cargo test --verbose --no-default-features --features parigot parigot
  - cargo test --verbose church

matrix:
  allow_failures:
    - rust: nightly

after_success:
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
  cargo bench --no-default-features;
  cargo bench --no-default-features --features scott scott;
  cargo bench --no-default-features --features parigot parigot;
  cargo bench church;
  fi
