language: rust

cache: cargo

sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --no-default-features
  - cargo build
  - cargo test

matrix:
  allow_failures:
    - rust: nightly
