language: rust

cache: cargo

sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose --no-default-features
  - cargo test --verbose church
  - cargo test --verbose scott
  - cargo test --verbose parigot
  - cargo test --verbose stumpfu

matrix:
  allow_failures:
    - rust: nightly

after_success:
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
  cargo bench --no-default-features;
  cargo bench church;
  cargo bench scott;
  cargo bench parigot;
  cargo bench stumpfu;
  fi
