[package]
name = "lambda_calculus"
version = "0.1.1"
description = "An implementation of the untyped lambda calculus in Rust"
repository = "https://github.com/ljedrz/lambda_calculus"
documentation = "https://ljedrz.github.io/lambda_calculus/doc/lambda_calculus/index.html"
readme = "README.md"
license = "CC0-1.0"
keywords = ["lambda", "calculus", "functional"]
authors = ["ljedrz <ljedrz@gmail.com>"]

[dependencies]
