[package]
name = "lambda_calculus"
version = "0.12.0"
description = "A simple implementation of the untyped lambda calculus in Rust."
repository = "https://github.com/ljedrz/lambda_calculus"
documentation = "https://docs.rs/lambda_calculus"
readme = "README.md"
license = "CC0-1.0"
keywords = ["lambda", "calculus", "church", "functional", "mathematics"]
authors = ["ljedrz <ljedrz@gmail.com>"]
exclude = [".cargo/*"]

[features]
backslash_lambda = []
no_church = []

[badges]
travis-ci = { repository = "ljedrz/lambda_calculus", branch = "master" }

[dependencies]
